[package]
name = "libmdns"
version = "0.2.4"
authors = ["Will Stott <willstott101+libmdns@gmail.com>"]

description = "mDNS Responder library for building discoverable LAN services in Rust"
repository = "https://github.com/librespot-org/libmdns"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
byteorder = "1.2"
futures = "0.1"
get_if_addrs = "0.5"
hostname = "0.2"
log = "0.4"
multimap = "0.4"
net2 = "0.2"
rand = "0.5"
tokio-core = "0.1"
quick-error = "1.2"

[dev-dependencies]
env_logger = "0.5"
